version: "3.5"

services:

  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pdp
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "$APP_PORT:4444"
    depends_on:
      - postgres
    volumes:
      - .:/app:delegated

volumes:
  postgres_data:
