export enum AuthMethod {
  PASSWORD = 'PASSWORD',
  GITHUB = 'GITHUB',
  GITLAB = 'GITLAB',
  BITBUCKET_CLOUD = 'BITBUCKET_CLOUD',
  JIRA_CLOUD = 'JIRA_CLOUD',
  TRELLO = 'TRELLO',
  BUDDY = 'BUDDY',
}
